# 生产环境
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13309/nebula-agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: nebula-agent
    password: '{A)MeKt,P_Xi1{y-'
  data:
    redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 17963
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接密码（默认为空）
      password: '@x{NDzAlj%%(&Z-j'

# 文件相关配置信息
file:
  access:
    address: https://nebula.qingsea.top
  share:
    address: https://nebula.qingsea.top/public/file/share/
  oss:
    endpoint: oss-cn-hangzhou-internal.aliyuncs.com