# 生产环境
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/nebula-agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  data:
    redis:
      # Redis服务器地址
#      host: 127.0.0.1
      host: 192.168.3.122
      # Redis服务器连接端口
      port: 6379
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器连接密码（默认为空）
#      password: '%FD@Aoa%l4Sv'
      password: 'sf2!Ka2#tE2AD+9g'

# 文件相关配置信息
file:
  access:
    address: http://127.0.0.1:9000
  share:
    address: http://localhost:5173/public/file/share/